# Generated by Django 4.1.5 on 2023-03-18 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 14, 1, 29, 304238, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 18)),
        ),
    ]
