# Generated by Django 4.1.5 on 2023-03-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_attendance', '0002_attendance_time_alter_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='time',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
