# Generated by Django 4.1.5 on 2023-02-05 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_attendance', '0002_admin_remove_attend_present'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attend',
            old_name='face_id',
            new_name='emp_id',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='face_id',
            new_name='emp_id',
        ),
        migrations.AddField(
            model_name='attend',
            name='dat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attend',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
