# Generated by Django 4.1.5 on 2023-02-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_attendance', '0003_rename_face_id_attend_emp_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='attend',
            new_name='attendance',
        ),
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='employee',
        ),
    ]
