# Generated by Django 4.1.5 on 2023-02-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_attendance', '0004_rename_attend_attendance_rename_userprofile_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='dat',
            new_name='date',
        ),
    ]
