# Generated by Django 4.1.5 on 2023-02-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee_attendance', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='attendance',
        ),
        migrations.DeleteModel(
            name='employee',
        ),
    ]
